In [3]:
#Завдання 1. Завантаження та огляд

import pandas as pd

df = pd.read_csv('tips.csv')

display(df.head())
display(df.shape)
display(df.columns)
display(df.info)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

(244, 7)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

<bound method DataFrame.info of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

In [4]:
#Завдання 2. Базова вибірка даних

total_bill = df['total_bill']
bill_and_tip = df[['total_bill', 'tip']]
#top_rows = df.head(10)
top_rows = df.head(10)
row_5 = df.iloc[5]

display(total_bill)
display(bill_and_tip)
display(top_rows)
display(row_5)

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

In [5]:
from IPython.core.interactiveshell import dis
#Завдання 3. Фільтрація даних

bill_over20 = df[df['total_bill'] > 20]
female_visitors = df[df['sex'] == 'Female']
dinner_bill = df[df['time'] == 'Dinner']
dinner_bill_over30 = df[(df['total_bill']>30) & (df['time'] == 'Dinner')]

print(f'Рахунки більше 20 доларів. Кількість записів: {len(bill_over20)}')
display(bill_over20.head(5))

print(f'Всі відвідувачі-жінки. Кількість записів: {len(female_visitors)}')
display(female_visitors.head(5))

print(f'Рахунки на вечерю. Кількість записів: {len(dinner_bill)}')
display(dinner_bill.head(5))

print(f'Рахунки на вечерю з сумою чеку більше 30 доларів. Кількість записів: {len(dinner_bill_over30)}')
display(dinner_bill_over30.head(5))

Рахунки більше 20 доларів. Кількість записів: 97

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

Всі відвідувачі-жінки. Кількість записів: 87

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

Рахунки на вечерю. Кількість записів: 176

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Рахунки на вечерю з сумою чеку більше 30 доларів. Кількість записів: 27

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

In [ ]:
print(f'Рахунки більше 20 доларів. Кількість записів: {len(bill_over20)}')
display(bill_over20.head(5))

Рахунки більше 20 доларів. Кількість записів: 97

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

In [7]:
from numpy import mean
#Завдання 4. Описова статистика

average_bill = df['total_bill'].mean().round(2)
print (f'Середня розмір рахунку: {average_bill}')

max_tip = df['tip'].max()
print (f'Максимальні чайові: {max_tip}')

null_count = df.isnull().sum().sum()
print (f'Кількість пропущенних значень: {null_count}')

dinner = df['time'].value_counts()['Dinner']
lunch = df['time'].value_counts()['Lunch']
print(f'Кількість рахунків за обіди: {lunch}, кількість рахунків за вечері: {dinner}')

Середня розмір рахунку: 19.79
Максимальні чайові: 10.0
Кількість пропущенних значень: 0
Кількість рахунків за обіди: 176, кількість рахунків за вечері: 68

In [ ]:
#Завдання 5. Статистика із групуванням

by_sex = df.groupby('sex')['total_bill'].mean().round(2)
print (by_sex)

tips_by_day = df.groupby('day')['tip'].mean().round(2)
print (tips_by_day)

visitors_by_day = df.groupby('day')['size'].sum()
print(visitors_by_day)

sex
Female    18.06
Male      20.74
Name: total_bill, dtype: float64
day
Fri     2.73
Sat     2.99
Sun     3.26
Thur    2.77
Name: tip, dtype: float64
day
Fri      40
Sat     219
Sun     216
Thur    152
Name: size, dtype: int64

In [ ]:
#Завдання 6. Створення нової колонки

df['tip_percentage'] = (df['tip'] / df['total_bill'] * 100).round(2)
display(df.head(10))

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2            5.94
1       10.34  1.66    Male     No  Sun  Dinner     3           16.05
2       21.01  3.50    Male     No  Sun  Dinner     3           16.66
3       23.68  3.31    Male     No  Sun  Dinner     2           13.98
4       24.59  3.61  Female     No  Sun  Dinner     4           14.68
5       25.29  4.71    Male     No  Sun  Dinner     4           18.62
6        8.77  2.00    Male     No  Sun  Dinner     2           22.81
7       26.88  3.12    Male     No  Sun  Dinner     4           11.61
8       15.04  1.96    Male     No  Sun  Dinner     2           13.03
9       14.78  3.23    Male     No  Sun  Dinner     2           21.85

In [8]:
#Завдання 7. Сортування

df_sorted_bill = df.sort_values('total_bill')
df_sorted_tip = df.sort_values('tip', ascending = False)
top_tip = df.nlargest(5, 'tip')

print("--- Сортування за розміром рахунку (зростання) ---")
display(df_sorted_bill.head(10))

print("\n--- Сортування за чайовими (спадання) ---")
display(df_sorted_tip.head(10))

print("\n--- Топ-5 найбільших чайових (через nlargest) ---")
display(top_tip)

--- Сортування за розміром рахунку (зростання) ---

     total_bill   tip     sex smoker   day    time  size
67         3.07  1.00  Female    Yes   Sat  Dinner     1
92         5.75  1.00  Female    Yes   Fri  Dinner     2
111        7.25  1.00  Female     No   Sat  Dinner     1
172        7.25  5.15    Male    Yes   Sun  Dinner     2
149        7.51  2.00    Male     No  Thur   Lunch     2
195        7.56  1.44    Male     No  Thur   Lunch     2
218        7.74  1.44    Male    Yes   Sat  Dinner     2
145        8.35  1.50  Female     No  Thur   Lunch     2
135        8.51  1.25  Female     No  Thur   Lunch     2
126        8.52  1.48    Male     No  Thur   Lunch     2

--- Сортування за чайовими (спадання) ---

     total_bill    tip     sex smoker   day    time  size
170       50.81  10.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
183       23.17   6.50    Male    Yes   Sun  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
47        32.40   6.00    Male     No   Sun  Dinner     4
239       29.03   5.92    Male     No   Sat  Dinner     3
88        24.71   5.85    Male     No  Thur   Lunch     2

--- Топ-5 найбільших чайових (через nlargest) ---

     total_bill    tip   sex smoker   day    time  size
170       50.81  10.00  Male    Yes   Sat  Dinner     3
212       48.33   9.00  Male     No   Sat  Dinner     4
23        39.42   7.58  Male     No   Sat  Dinner     4
59        48.27   6.73  Male     No   Sat  Dinner     4
141       34.30   6.70  Male     No  Thur   Lunch     6